name: hik
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.0=h5c54ea9_2
  - cyrus-sasl=2.1.28=h6c5dea3_0
  - dbus=1.16.2=heda779d_0
  - expat=2.7.3=h5b11e9f_4
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=hfa97f67_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=h8af1aa0_0
  - graphite2=1.3.14=hfae3067_2
  - gst-plugins-base=1.24.12=hd473972_1
  - gstreamer=1.24.12=hb60ce7b_1
  - gstreamer-orc=0.4.42=h70b131a_0
  - harfbuzz=10.2.0=h6cf3ae6_1
  - icu=73.2=h787c7f5_0
  - jpeg=9e=h2a766a3_3
  - keyutils=1.6.3=h86ecc28_0
  - krb5=1.21.3=h50a48e9_0
  - ld_impl_linux-aarch64=2.44=h4e4ac68_2
  - libclang13=21.1.0=default_h94a09a5_1
  - libcups=2.4.15=hd8206d2_0
  - libdrm=2.4.125=he30d5cf_1
  - libedit=3.1.20250104=pl5321h976ea20_0
  - libegl=1.7.0=hd24410f_2
  - libexpat=2.7.3=h5b11e9f_4
  - libffi=3.4.4=h419075a_1
  - libfreetype=2.14.1=h8af1aa0_0
  - libfreetype6=2.14.1=hdae7a39_0
  - libgcc=15.2.0=hc18542e_7
  - libgcc-ng=15.2.0=h51576c1_7
  - libgl=1.7.0=hd24410f_2
  - libglib=2.84.4=haa79c35_1
  - libglvnd=1.7.0=hd24410f_2
  - libglx=1.7.0=hd24410f_2
  - libgomp=15.2.0=hf47c802_7
  - libiconv=1.18=h90929bb_2
  - libkrb5=1.21.3=hfa9a360_4
  - libllvm20=20.1.8=h2b567e5_0
  - libllvm21=21.1.0=h2b567e5_0
  - libnsl=2.0.0=h998d150_0
  - libntlm=1.4=hf897c2e_1002
  - libogg=1.3.5=h86ecc28_1
  - libopengl=1.7.0=hd24410f_2
  - libopus=1.6.1=h80f16a2_0
  - libpciaccess=0.18=h86ecc28_0
  - libpng=1.6.54=h1abf092_0
  - libpq=17.6=h9cc9b1a_0
  - libstdcxx=15.2.0=h9538471_7
  - libstdcxx-ng=15.2.0=h719ae8e_7
  - libuuid=1.41.5=h998d150_0
  - libvorbis=1.3.7=h7ac5ae9_2
  - libxcb=1.17.0=hf66535e_0
  - libxcrypt=4.4.36=h31becfc_1
  - libxkbcommon=1.11.0=h95ca766_0
  - libxml2=2.13.9=h729a2f8_0
  - libzlib=1.3.1=h998d150_0
  - lmdb=0.9.31=h31becfc_1
  - mysql-common=9.3.0=h3f5c77f_0
  - mysql-libs=9.3.0=h11569fd_0
  - ncurses=6.5=h419075a_0
  - openldap=2.6.10=h30c48ee_0
  - openssl=3.6.0=h8e36d6e_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.46=h15761aa_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7ac5ae9_1
  - ply=3.11=pyhd8ed1ab_3
  - pthread-stubs=0.3=hfd63f10_1
  - pyqt=5.15.11=py310h68c0612_0
  - pyqt5-sip=12.17.0=py310ha28494d_0
  - python=3.10.19=h81fb49f_0
  - python_abi=3.10=2_cp310
  - qt-main=5.15.2=ha043035_13
  - readline=8.3=h886d1d0_0
  - setuptools=80.9.0=py310hd43f75c_0
  - sip=6.12.0=py310hbe5e9e6_1
  - sqlite=3.51.1=hcfd1b6d_0
  - tk=8.6.15=h987d8db_0
  - tomli=2.4.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hd43f75c_0
  - xcb-util=0.4.1=hca56bd8_2
  - xcb-util-image=0.4.0=h5c728e9_2
  - xcb-util-keysyms=0.4.1=h5c728e9_0
  - xcb-util-renderutil=0.3.10=h5c728e9_0
  - xcb-util-wm=0.4.2=h5c728e9_0
  - xkeyboard-config=2.46=he30d5cf_0
  - xorg-libice=1.1.2=h86ecc28_0
  - xorg-libsm=1.2.6=hf66535e_0
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxcomposite=0.4.6=h86ecc28_2
  - xorg-libxdamage=1.1.6=h86ecc28_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-libxext=1.3.6=h57736b2_0
  - xorg-libxfixes=6.0.2=he30d5cf_0
  - xorg-libxrender=0.9.12=h86ecc28_0
  - xorg-libxxf86vm=1.1.6=h86ecc28_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - zlib=1.3.1=h998d150_0
  - zstd=1.5.7=h85ac4a6_6
  - pip:
      - blinker==1.9.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - crcmod==1.7
      - esdk-obs-python==3.25.8
      - flask==3.1.2
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pycryptodome==3.23.0
      - requests==2.32.5
      - urllib3==2.6.3
      - werkzeug==3.1.5
prefix: /home/xtc/.conda/envs/hik
